# Site settings
title: Amit Bendor
description: Amit Bendor, Entrepreneur and chatbot consultant, Leader of The Israeli Bots community & Co-Hosting the "Making software" Podcast 
keywords: "Bots, Chatbot, Voicebot, Actions on google, Google assistant, skills, Cortana, Amit , Bendor ,CTO"
author: "Amit Bendor"
url: "https://amitbend.com"
#url: "http://localhost:3000"

# User settings
username: Amit BenDor  
user_title: Chatbot & Voicebot Specialist
email: me@amitbend.com
github_username: amitbend
linkedin_username: amitbendor
npm_username: amitbend
medium_username: amitbd
stackoverflow_url: 4156209/amit-be
# Google-analytics
google-analytics:
  id: "UA-121328300-1"


exclude: ['package.json', 'src' , 'node_modules']
