# Site settings
title: Amit Bendor | Practical AI/ML Expert
description: Entrepreneur and chatbot consultant, Leader of The Israeli Bots community & Co-Hosting the "Making software" Podcast 
keywords: "Bots, Chatbot, Voicebot, Actions on google, Google assistant, skills, Cortana, Amit , Bendor ,CTO, Consulting"
author: "Amit Bendor"
url: "https://amitbend.com"
image: "/assets/img/me2.png"

# User settings
username: Amit BenDor  
user_title: Practical AI/ML Expert
email: me@amitbend.com
github_username: amitbend
linkedin_username: amitbendor
npm_username: ~amitbend
medium_username: amitbd
stackoverflow_url: 4156209/amit-be
# Google-analytics
google-analytics:
  id: "UA-121328300-1"

sass:
    style: compressed

plugins:
  - jekyll-seo-tag
  - jekyll-assets
  - amp-jekyll
  - jekyll-feed

# image optim
assets:
  plugins:
    img:
      optim:
        {}

# seo
facebook:
  app_id: 1252810241395987
  publisher: 1638322646389732
  admins: 1039746660



# logo:

exclude: ['package.json', 'src' , 'node_modules', 'vendor/bundle/']
